files:
  - source: /src/main/resources/assets/*/lang/en_us.json
    translation: /%original_path%/lang/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/en_us.json
    translation: /src/main/resources/assets/nomansland/lang/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/nomansland/dialogue_pools/contextual/template.json
    translation: /src/main/resources/assets/nomansland/lang/nomansland/dialogue_pools/contextual/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/nomansland/dialogue_pools/greeting/template.json
    translation: /src/main/resources/assets/nomansland/lang/nomansland/dialogue_pools/greeting/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/nomansland/dialogue_pools/leaving/template.json
    translation: /src/main/resources/assets/nomansland/lang/nomansland/dialogue_pools/leaving/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/nomansland/dialogue_pools/negative/template.json
    translation: /src/main/resources/assets/nomansland/lang/nomansland/dialogue_pools/negative/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/nomansland/dialogue_pools/offering/en_us.json
    translation: /src/main/resources/assets/nomansland/lang/nomansland/dialogue_pools/offering/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/nomansland/dialogue_pools/passive/template.json
    translation: /src/main/resources/assets/nomansland/lang/nomansland/dialogue_pools/passive/%locale_with_underscore%.json
  - source: /src/generated/resources/assets/nomansland/lang/nomansland/dialogue_pools/special/template.json
    translation: /src/main/resources/assets/nomansland/lang/nomansland/dialogue_pools/special/%locale_with_underscore%.json
